### ISSUE TITLE
Unable to activate Plugin in Godot 3.1

### ISSUE THREAD

**Issue by Cnidarias** [Zylann/godot_heightmap_plugin#71]
I am having issues installing the plugin.

I have tried several combinations:

| Godot Version | PluginVersion | ActivationResult |
|---------------|---------------|------------------|
| 3.1 beta 1    | master        |  F               |
| 3.1 beta 1    | 0.10          | F                |
| 3.1 beta 4    | master        | F                |
| 3.1 beta 4    | 0.10          | F                |
| 3.1 master    | master        | F                |
| 3.1 master    | 0.10          | F                |
| 3.0.6         | 0.10          | Okay             |

With every combination I receive these errors:

```
SCRIPT ERROR: GDScript::reload: Parse Error: Function signature doesn't match the parent. Parent signature is: 'Texture generate(Resource, Vector2)'.
          At: res://addons/zylann.hterrain/tools/preview_generator.gd:11
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
          At: res://addons/zylann.hterrain/tools/plugin.gd:8
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579
SCRIPT ERROR: GDScript::reload: Parse Error: Function signature doesn't match the parent. Parent signature is: 'Texture generate(Resource, Vector2)'.
          At: res://addons/zylann.hterrain/tools/preview_generator.gd:11
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
          At: res://addons/zylann.hterrain/tools/plugin.gd:8
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579
```

Maybe I am just missing something obvious?

The import of the plugin does seem to work with godot 3.0.6 though.

**Comment by Cnidarias** [comment]
Alright. For some odd reason there was some issue with git when changing the branches and it decided it wouldn't want to change one file from the 0.10 branch to the master branch.

The import with the current master branch does seem to work as intended

**Comment by shayneoneill** [comment]
Bump. Is there going to be a fix for this?
