### ISSUE TITLE
preview_generator.gd fails in 3.1.Alpha4

### ISSUE THREAD

**Issue by FeralBytes** [Zylann/godot_heightmap_plugin#62]
Tried to install the plugin on Godot 3.1.Alpha 4 official and it failed to load with an error of:
```
Unable to load addon script from path 'res://addons/zylann.hterrain/tools/plugin.gd' There seems to be an error in the code, please check the syntax.
```
```
Godot Engine v3.1.alpha.official (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
 res://addons/zylann.hterrain/tools/preview_generator.gd:11 - Parse Error: Function signature doesn't match the parent. Parent signature is: 'Texture generate(Resource, Vector2)'.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/tools/plugin.gd:8 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/tools/preview_generator.gd:11 - Parse Error: Function signature doesn't match the parent. Parent signature is: 'Texture generate(Resource, Vector2)'.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
```
Downloaded zip from GitHub extracted the addons folder into the Godot project. Then in project settings -> plugin tab changed to active and failed.

**Comment by Zylann** [comment]
(sorry mistapped the close button)

Godot broke compatibility of this API in 3.1, so currently the master branch of my plugin and 0.10 on the assetlib don't work well in Godot 3.1.

I started working on this version though, if you want to try a development version that should work in 3.1, check the `saving` branch.

**Comment by FeralBytes** [comment]
Thanks Zylann. I will give it a try and report back soon.

**Comment by FeralBytes** [comment]
@Zylann 
`saving` branch failed in 3.1.a4 too but with a different error.
```
res://addons/zylann.hterrain/tools/plugin.gd:19 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
```
Line 19 is a preload that looks like this:
```
const GlobalMapBaker = preload("globalmap_baker.gd")
```
## Steps to reproduce:
I put the `saving` branch of zylann.hterrain into the addon folder and then tried to activate the plugin in the project settings.

**Comment by Zylann** [comment]
@FeralBytes Is it happening again if you restart the editor?
I have no idea what could be going on here.

**Comment by FeralBytes** [comment]
@Zylann no, actually that fixed the error. I remember reading that you are waiting for them to add an ability to reload the editor and that it needs to be added to the API. But it would probably be a good idea for the editor to save and restart any time an addon is added, due to false issues like this. Thanks!

**Comment by Zylann** [comment]
@FeralBytes I have issues like that with many plugins: https://github.com/godotengine/godot/issues/23937

**Comment by FeralBytes** [comment]
@Zylann since I have your attention for a moment, I realize this is not a support forum. 
Is it possible to export the height terrain from Godot and back into blender for texture and detailing. Or would this incur a performance penalty or worse break all together?
Second how many hterrains can I have in a single scene, what are some performance limits you have noticed and at what sizes? Any computer spec details would also be handy for me, thank you for your time.

**Comment by Zylann** [comment]
@FeralBytes you mean you want the heightmap as an image? If you want to do this, it has to be saved either as `raw`, or as `exr` but https://github.com/Zylann/godot_heightmap_plugin/issues/34 is in the way. It could be saved as PNG but you would loose precision tremendously.

You can have any number of terrains you want, but there are indeed hardware limits. I was able to run terrains ranging from 513x513 to 4097x4097. I think higher would work too on recent graphics cards, but to make terrains that big I would prefer relying on streaming instead, which I theorized in https://github.com/Zylann/godot_heightmap_plugin/issues/55.

**Comment by FeralBytes** [comment]
@Zylann No I wanted it as a mesh in blender so I could paint it and manipulate it further. I see the ability to convert the hterrain into a mesh but there is a warning. I understand LOD is Level Of Detail; so what you are saying is; as a mesh Godot will always utilize a full LOD across the hterrain rather than only for a certain range? I can see how that would be a serious performance impact.

I was theorizing that I could have a setup which I will detail below imagine that there is a grid of 3x3 hterrains and the player is currently standing on the middle one; designated by the letter P and assume the player is heading to the right. These are the 9 grids that I load as the player transitions I load the new 3x3 ocasionally loading up to 10-12 grids to give the player a better view on the horrizon.
```
-----------        --------------
|    |    |    |         |    |    |    |    |
-----------        --------------
|    | P |    |         |    | P |    |    |
-----------        --------------
|    |    |    |         |    |    |    |    |
-----------        --------------
```
513x513 seems pretty large to manage this scheme. This also makes me wonder why not smaller terrain sizes as an option? And why not powers of 2?

**Comment by Zylann** [comment]
If you want to edit the terrain externally, a dedicated heightmap editor would be better suited. I know mostly about WorldMachine, Scape and Lithosphere, perhaps there are others. But in general, they work on images, not meshes, precisely because they are way too big and image processing is more efficient.

Usage of powers of two in terrain sizes is needed for LOD to work properly, otherwise it will be unbalanced/less efficient because it would have to account for partial regions that don't fall within chunk boundaries.

Smaller than 513x513 is supported, but I felt there was no much use cases under this size. I could unlock 257x257, but Tthe real smallest size you can get is 33x33, which is the size of one geomety chunk.
If the reason is to put terrains in a grid pattern like you described, this would not work without a significant amount of tweaks to both runtime and terrain data to avoid seams. That's why I wanted to make this built-in, to deal with this more efficiently and keep it consistent in the editor.

**Comment by Zylann** [comment]
Oh ok so it's actually power of two + 1 because of this: https://github.com/Zylann/godot_heightmap_module/blob/master/height_map_data.cpp#L22
It boils down to the fact that to make a 1x1 quad, you need 2x2 pixels in the heightmap. But to make LOD working, you need an even number of quads, so... you need an uneven number of pixels. You will see the same sizes offered in Unity, and Unreal also takes an approach with different sizes.
However, I understand it might be suboptimal for memory on some graphics cards: https://github.com/Zylann/godot_heightmap_plugin/issues/12

About seams, it's not only about the height, but normals too, and texture filtering as well, as neighboring pixels need to be shared across sectors. I've been thinking about this for a long time, and supporting this with separate terrain nodes in the same scene is quite a hassle IMO. Also, if you had multiple terrains, they would not know about each other and would have separate data that you have to choose the location for each, while a built-in implementation allows for a unique terrain folder.
Painting on multiple terrains could be done, but the only use case for it would be inexistent if sectors worked out of the box rather than manually made. You can try to do it by yourself though.

**Comment by FeralBytes** [comment]
Ok and thank you again for the explanations. Do you really think a built-in solution is possible given the "Engine Bloat" Issue? 
How can I help with the streaming? Do you have a road map of how we can get there?
Also I would like to add some documentation to the project in /docs/ folder, would you be Ok with a PR? I think it might help reduce the number of questions asked by people like me.

**Comment by Zylann** [comment]
By "built-in", I meant "built-in this plugin", not in Godot Engine (although that would be nice too).

For streaming there is just the issue I linked, nothing else. I want to finish migration to 3.1 first because it brings a few features and fixes that can help UX a lot, and notably the way the plugin ask you to create, load and save terrain data so far in the editor.

Only then, I will start writing docs for good and an API reference (some of it already exists as comments in the code), and switch the plugin to be version 1.0. Right now I'm working on fixing #57 first, because it's a big blocker^^
You can PR docs too, I didn't write docs on how to write the doc though xD The only thing right now is to use Markdown. In the worst case I will integrate it when making the proper doc.
