### ISSUE TITLE
Collider not working with map_scale != 1 on Godot 3.1 beta3

### ISSUE THREAD

**Issue by fonspa** [Zylann/godot_heightmap_plugin#70]
Hi,

I can't seem to get the collisions to work on a terrain I made in Godot 3.1 beta 3 although the demo you provide with your addon works OK in this version of the engine (however, I'm unable to activate the addon and thus can't use it to create or modify a terrain, only to load one. There's a problem with cyclic dependencies and preloading of gd scripts).
My terrain scene has collisions working in 3.0.6 but not in 3.1. Do you have any idea as to why ?
Thanks.

**Comment by Zylann** [comment]
What is this cyclic dependency bug? I keep hearing of one but everytime it's a false positive, as I can't figure out anything in the plugin that could cause that. Of course I also tried collisions and they work here as well...

**Comment by fonspa** [comment]
Hi,
The version I tried on the 3.1 is your latest version, on the master branch. On the 3.0.6 I was using the .10 branch.
I would also really want to know what is this cyclic bug. Your addon is not the only one affected. I use two other addons which don't work on the 3.1 because of the same bug and I find nothing on Internet about that.
![image](https://user-images.githubusercontent.com/13216575/52531350-ec15f000-2d13-11e9-9477-2aadd363da71.png)
![image](https://user-images.githubusercontent.com/13216575/52531351-f801b200-2d13-11e9-95a4-ab2e828c319b.png)
And I also get this bug on a fresh project with nothing but the addon.

I'm sorry for the inconvenience, I'd like to know more about this bug, it's certainly engine related.
Thanks for your great mod either way.

**Comment by Zylann** [comment]
Can you send me your project?

**Comment by wvffle** [comment]
I just tried to install it and I'm facing same error:
```
 res://addons/zylann.hterrain/tools/plugin.gd:8 - Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
 modules/gdscript/gdscript.cpp:579 - Method/Function Failed, returning: ERR_PARSE_ERROR
```

**Comment by Zylann** [comment]
@wvffle the version on the asset lib is not compatible with Godot 3.1 because there was a compatibility breakage in the plugin API.

**Comment by fonspa** [comment]
Of course, here it is [TestProject](https://filesender.renater.fr/?s=download&token=63fdeda7-cd06-2f0b-61a9-0714cfc2eb2f)
tell me if you have any problem downloading it.
Thanks

**Comment by Zylann** [comment]
I could not figure out what is wrong with my code, but what I see is that the Bullet collider returns hits in this region if `map_scale` is 2:

![image](https://user-images.githubusercontent.com/1311555/52536694-de815a00-2d55-11e9-8ccd-a80be63463fe.png)

Which means yet another thing Bullet heightfield collider appears to not handle correctly :/

**Comment by Zylann** [comment]
Sadly this is indeed another feature Godot does not exposes properly. I am sending a transform with scaling factored in to correctly apply to the heightmap collider, but Godot is undoing my scaling here https://github.com/godotengine/godot/blob/master/modules/bullet/collision_object_bullet.cpp#L53

Even though Bullet heightfields really support scaling: https://github.com/godotengine/godot/blob/master/thirdparty/bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h#L154

I can't fix this for 3.1, there has to be a PR to fix this in the engine...

**Comment by fonspa** [comment]
Thank you very much for your investigation.
I'll find a way around the scaling for now.

**Comment by Zylann** [comment]
@fonspa hang on, actually I found a fix.
I was using `shape transform`, but using `body transform` instead appears to work, so I'll test that and push it once it's done :)

**Comment by Zylann** [comment]
Should be fixe dby 6ddf4d668601e1897e64458095a105ec2cc84665, let me know if it works for you

**Comment by fonspa** [comment]
It does ! No more problems with any scaling now.
I'm glad you found the fix so quickly.
Thank you very much, your addon is definitely on the right track.
